In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("data/Train.csv",parse_dates=["saledate"],low_memory=False)

In [14]:
df

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,saledate,...,Undercarriage_Pad_Width,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls
0,1139246,66000,999089,3157,121,3.0,2004,68.0,Low,2006-11-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
1,1139248,57000,117657,77,121,3.0,1996,4640.0,Low,2004-03-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
2,1139249,10000,434808,7009,121,3.0,2001,2838.0,High,2004-02-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1139251,38500,1026470,332,121,3.0,2001,3486.0,High,2011-05-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1139253,11000,1057373,17311,121,3.0,2007,722.0,Medium,2009-07-23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401120,6333336,10500,1840702,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401121,6333337,11000,1830472,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401122,6333338,11500,1887659,21439,149,1.0,2005,NaN,NaN,2011-11-02,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401123,6333341,9000,1903570,21435,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN
401124,6333342,7750,1926965,21435,149,2.0,2005,NaN,NaN,2011-10-25,...,None or Unspecified,None or Unspecified,None or Unspecified,None or Unspecified,Double,NaN,NaN,NaN,NaN,NaN

In [8]:
df["UsageBand"].value_counts()

Medium    33985
Low       23620
High      12034
Name: UsageBand, dtype: int64

In [35]:
def train_cats(df):
    for n,c in df.items():
        if c.dtype=="object":
            df[n]=c.astype("category").cat.as_ordered()

In [36]:
train_cats(df)

int64
int64
int64
int64
int64
float64
int64
float64
object
datetime64[ns]
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object
object

In [37]:
df["UsageBand"].cat.categories

Index(['High', 'Low', 'Medium'], dtype='object')

In [40]:
df["UsageBand"].cat.set_categories(["High","Medium","Low"],ordered=True,inplace=True)

In [42]:
df["UsageBand"].cat.codes

0         2
1         2
2         0
3         0
4         1
         ..
401120   -1
401121   -1
401122   -1
401123   -1
401124   -1
Length: 401125, dtype: int8

In [28]:
dir(df["UsageBand"].dtype)

['__bool__',
 '__class__',
 '__class_getitem__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'alignment',
 'base',
 'byteorder',
 'char',
 'descr',
 'fields',
 'flags',
 'hasobject',
 'isalignedstruct',
 'isbuiltin',
 'isnative',
 'itemsize',
 'kind',
 'metadata',
 'name',
 'names',
 'ndim',
 'newbyteorder',
 'num',
 'shape',
 'str',
 'subdtype',
 'type']

In [34]:
df["UsageBand"].dtype.kind

'O'

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401125 entries, 0 to 401124
Data columns (total 53 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   SalesID                   401125 non-null  int64
 1   SalePrice                 401125 non-null  int64
 2   MachineID                 401125 non-null  int64
 3   ModelID                   401125 non-null  int64
 4   datasource                401125 non-null  int64
 5   auctioneerID              380989 non-null  float64
 6   YearMade                  401125 non-null  int64
 7   MachineHoursCurrentMeter  142765 non-null  float64
 8   UsageBand                 69639 non-null   object
 9   saledate                  401125 non-null  datetime64[ns]
 10  fiModelDesc               401125 non-null  object
 11  fiBaseModel               401125 non-null  object
 12  fiSecondaryDesc           263934 non-null  object
 13  fiModelSeries             56908 non-null   object
 14  fiModelDescriptor         71919 non-null   object
 15  ProductSize               190350 non-null  object
 16  fiProductClassDesc        401125 non-null  object
 17  state                     401125 non-null  object
 18  ProductGroup              401125 non-null  object
 19  ProductGroupDesc          401125 non-null  object
 20  Drive_System              104361 non-null  object
 21  Enclosure                 400800 non-null  object
 22  Forks                     192077 non-null  object
 23  Pad_Type                  79134 non-null   object
 24  Ride_Control              148606 non-null  object
 25  Stick                     79134 non-null   object
 26  Transmission              183230 non-null  object
 27  Turbocharged              79134 non-null   object
 28  Blade_Extension           25219 non-null   object
 29  Blade_Width               25219 non-null   object
 30  Enclosure_Type            25219 non-null   object
 31  Engine_Horsepower         25219 non-null   object
 32  Hydraulics                320570 non-null  object
 33  Pushblock                 25219 non-null   object
 34  Ripper                    104137 non-null  object
 35  Scarifier                 25230 non-null   object
 36  Tip_Control               25219 non-null   object
 37  Tire_Size                 94718 non-null   object
 38  Coupler                   213952 non-null  object
 39  Coupler_System            43458 non-null   object
 40  Grouser_Tracks            43362 non-null   object
 41  Hydraulics_Flow           43362 non-null   object
 42  Track_Type                99153 non-null   object
 43  Undercarriage_Pad_Width   99872 non-null   object
 44  Stick_Length              99218 non-null   object
 45  Thumb                     99288 non-null   object
 46  Pattern_Changer           99218 non-null   object
 47  Grouser_Type              99153 non-null   object
 48  Backhoe_Mounting          78672 non-null   object
 49  Blade_Type                79833 non-null   object
 50  Travel_Controls           79834 non-null   object
 51  Differential_Type         69411 non-null   object
 52  Steering_Controls         69369 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(6), object(44)
memory usage: 162.2+ MB