In [13]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import *

In [4]:
data=pd.read_csv("data.csv")

In [5]:
data

       X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0    0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1    0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2    0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3    0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4    0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28
..    ...    ...    ...     ...  ...  ..  ...  ..    ...    ...
763  0.64  784.0  343.0  220.50  3.5   5  0.4   5  17.88  21.40
764  0.62  808.5  367.5  220.50  3.5   2  0.4   5  16.54  16.88
765  0.62  808.5  367.5  220.50  3.5   3  0.4   5  16.44  17.11
766  0.62  808.5  367.5  220.50  3.5   4  0.4   5  16.48  16.61
767  0.62  808.5  367.5  220.50  3.5   5  0.4   5  16.64  16.03

[768 rows x 10 columns]

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X1      768 non-null    float64
 1   X2      768 non-null    float64
 2   X3      768 non-null    float64
 3   X4      768 non-null    float64
 4   X5      768 non-null    float64
 5   X6      768 non-null    int64
 6   X7      768 non-null    float64
 7   X8      768 non-null    int64
 8   Y1      768 non-null    float64
 9   Y2      768 non-null    float64
dtypes: float64(8), int64(2)
memory usage: 60.1 KB

In [7]:
data.describe()

,X1,X2,X3,X4,X5,X6,X7,X8,Y1,Y2
count,768.000000,768.000000,768.000000,768.000000,768.00000,768.000000,768.000000,768.00000,768.000000,768.000000
mean,0.764167,671.708333,318.500000,176.604167,5.25000,3.500000,0.234375,2.81250,22.307201,24.587760
std,0.105777,88.086116,43.626481,45.165950,1.75114,1.118763,0.133221,1.55096,10.090196,9.513306
min,0.620000,514.500000,245.000000,110.250000,3.50000,2.000000,0.000000,0.00000,6.010000,10.900000
25%,0.682500,606.375000,294.000000,140.875000,3.50000,2.750000,0.100000,1.75000,12.992500,15.620000
50%,0.750000,673.750000,318.500000,183.750000,5.25000,3.500000,0.250000,3.00000,18.950000,22.080000
75%,0.830000,741.125000,343.000000,220.500000,7.00000,4.250000,0.400000,4.00000,31.667500,33.132500
max,0.980000,808.500000,416.500000,220.500000,7.00000,5.000000,0.400000,5.00000,43.100000,48.030000

In [11]:
Y1=data["Y1"]
Y2=data["Y2"]
X=data.iloc[:,0:8]

In [212]:
model1=RandomForestRegressor()
model2=RandomForestRegressor(max_features="sqrt")
for _ in range(150):
    X_train,X_test,Y_train1,Y_test1=train_test_split(X,Y1,train_size=0.80)
    Y_test2=Y2[Y_test1.index]
    Y_train2=Y2[Y_train1.index]
    
    model1.fit(X_train.values,Y_train1.values)
    model2.fit(X_train.values,Y_train2.values)
    
    y1_predict=model1.predict(X_test.values)
    y2_predict=model2.predict(X_test.values)
    y1_error = mean_absolute_error(y1_predict,Y_test1.values)
    y2_error = mean_absolute_error(y2_predict,Y_test2.values)
    if y1_error < 0.30 and y2_error <0.82:
        break
    print({"Heating Load":y1_error,"Cooling Load":y2_error})

{'Heating Load': 0.34241363636363575, 'Cooling Load': 0.9640594155844144}
{'Heating Load': 0.2913032467532482, 'Cooling Load': 0.8887525974025979}
{'Heating Load': 0.2906616883116877, 'Cooling Load': 0.9775974025974001}
{'Heating Load': 0.3208753246753225, 'Cooling Load': 0.8954451298701288}
{'Heating Load': 0.3343798701298696, 'Cooling Load': 1.0869282467532457}
{'Heating Load': 0.34881428571428597, 'Cooling Load': 1.1714573593073578}
{'Heating Load': 0.30473506493506575, 'Cooling Load': 0.895150649350649}
{'Heating Load': 0.3760577922077876, 'Cooling Load': 1.058025324675323}
{'Heating Load': 0.35842662337662184, 'Cooling Load': 1.0509545454545464}
{'Heating Load': 0.31282987012987046, 'Cooling Load': 1.065213636363635}
{'Heating Load': 0.3189649350649366, 'Cooling Load': 1.1056545454545463}
{'Heating Load': 0.3119733766233798, 'Cooling Load': 1.023646753246753}
{'Heating Load': 0.29927922077922425, 'Cooling Load': 0.8607863636363621}
{'Heating Load': 0.27729220779220876, 'Cooling Load': 0.9450954545454536}
{'Heating Load': 0.35226948051948215, 'Cooling Load': 1.0245870129870123}
{'Heating Load': 0.3906779220779229, 'Cooling Load': 1.1445545454545434}
{'Heating Load': 0.3207071428571428, 'Cooling Load': 0.9591110389610388}
{'Heating Load': 0.3132045454545466, 'Cooling Load': 0.9509547619047639}
{'Heating Load': 0.30639220779220433, 'Cooling Load': 1.0577636363636376}
{'Heating Load': 0.32258051948051747, 'Cooling Load': 1.0949448051948047}
{'Heating Load': 0.32486883116883447, 'Cooling Load': 1.057069047619048}
{'Heating Load': 0.33982077922077875, 'Cooling Load': 1.0668980519480513}
{'Heating Load': 0.3172525974025982, 'Cooling Load': 0.9058889610389612}
{'Heating Load': 0.34112012987013146, 'Cooling Load': 1.096465367965366}
{'Heating Load': 0.2983272727272701, 'Cooling Load': 0.8701324675324676}
{'Heating Load': 0.37106038961038873, 'Cooling Load': 1.127914610389608}
{'Heating Load': 0.33834935064935295, 'Cooling Load': 1.093530519480518}
{'Heating Load': 0.32730259740259554, 'Cooling Load': 0.9672558441558442}
{'Heating Load': 0.28601233766233713, 'Cooling Load': 0.9105893939393933}
{'Heating Load': 0.36241688311688536, 'Cooling Load': 1.0382461038961057}
{'Heating Load': 0.3514136363636367, 'Cooling Load': 1.0156372077922067}
{'Heating Load': 0.40739805194805184, 'Cooling Load': 1.062371428571425}
{'Heating Load': 0.33006883116883334, 'Cooling Load': 0.9276905844155833}
{'Heating Load': 0.2973662337662332, 'Cooling Load': 1.0178969696969695}
{'Heating Load': 0.31757662337662423, 'Cooling Load': 0.9417688311688303}
{'Heating Load': 0.3423753246753252, 'Cooling Load': 0.9981831168831177}
{'Heating Load': 0.3055785714285746, 'Cooling Load': 0.8930253246753235}
{'Heating Load': 0.33150519480519647, 'Cooling Load': 1.112339393939393}

In [214]:
class Model:
    def __init__(self,model1,model2):
        self.model1=model1
        self.model2=model2
    def predict(self,X):
        return {"Heating Load":self.model1.predict(X)[0],"Cooling Load":self.model2.predict(X)[0]}

In [217]:
model = Model(model1,model2)
model.predict(X_test.iloc[0].values.reshape(1,-1))

{'Heating Load': 15.269700000000014, 'Cooling Load': 19.58339999999999}

In [219]:
Y_test2.iloc[0]

19.23

In [220]:
pd.to_pickle(model,"random_forest_model.pkl")

In [221]:
m = pd.read_pickle("random_forest_model.pkl")
m.predict(X_test.iloc[0].values.reshape(1,-1))

{'Heating Load': 15.269700000000014, 'Cooling Load': 19.58339999999999}